/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tugasuas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maulana Jaelani
 */
public class form extends javax.swing.JFrame {
    private boolean databaru;
    koneksi con= new koneksi();
    int fNilai;
    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        NoDaf.setEnabled(false);
        Bupdate.setEnabled(false);
        Bdelete.setEnabled(false);
        getData();
        buatId();
        databaru = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        Binsert = new javax.swing.JButton();
        Bupdate = new javax.swing.JButton();
        Bdelete = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fcari = new javax.swing.JTextField();
        comCari = new javax.swing.JComboBox<>();
        Bcari = new javax.swing.JButton();
        NoDaf = new javax.swing.JTextField();
        fnama = new javax.swing.JTextField();
        ftempat = new javax.swing.JTextField();
        falamat = new javax.swing.JTextField();
        fsekolah = new javax.swing.JTextField();
        fnilai = new javax.swing.JTextField();
        fwali = new javax.swing.JTextField();
        fhp = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("FORM PENDAFTARAN SISWA BARU");

        jLabel2.setText("NO PENDAFTARAN :");

        jLabel3.setText("NAMA LENGKAP :");

        jLabel4.setText("TANGGAL LAHIR :");

        jLabel5.setText("TEMPAT LAHIR :");

        jLabel6.setText("JENIS KELAMIN :");

        jLabel7.setText("ALAMAT :");

        jLabel8.setText("NO HP :");

        jLabel9.setText("ASAL SEKOLAH :");

        jLabel10.setText("NAMA WALI :");

        jLabel11.setText("NILAI UAN :");

        buttonGroup1.add(laki);
        laki.setText("laki-laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(perempuan);
        perempuan.setText("perempuan");

        Binsert.setText("insert");
        Binsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinsertActionPerformed(evt);
            }
        });

        Bupdate.setText("update");
        Bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupdateActionPerformed(evt);
            }
        });

        Bdelete.setText("delete");
        Bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdeleteActionPerformed(evt);
            }
        });

        Breset.setText("Batal");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(240, 240, 240));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor Pendaftaran", "Nama Lengkap", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "Asal Sekolah", "Nilai Uan", "Nama Ortu", "No Telp"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        fcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcariActionPerformed(evt);
            }
        });

        comCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Pendaftaran", "Nama", "Jenis kelamin", "Nilai" }));

        Bcari.setText("Cari");
        Bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcariActionPerformed(evt);
            }
        });

        NoDaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoDafActionPerformed(evt);
            }
        });

        fnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamaActionPerformed(evt);
            }
        });

        ftempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftempatActionPerformed(evt);
            }
        });

        falamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falamatActionPerformed(evt);
            }
        });

        fsekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsekolahActionPerformed(evt);
            }
        });

        fnilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnilaiActionPerformed(evt);
            }
        });

        fwali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fwaliActionPerformed(evt);
            }
        });

        fhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fwali, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fhp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addComponent(Binsert, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Breset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(falamat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(laki)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(perempuan))
                                            .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ftempat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fsekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fnilai, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fcari, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comCari, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(Bcari))))
                            .addComponent(NoDaf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NoDaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ftempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(laki)
                                    .addComponent(perempuan))
                                .addGap(32, 32, 32))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(falamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(fsekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(fnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(fwali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(fhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bcari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Binsert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Breset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void fcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcariActionPerformed

    private void NoDafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoDafActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoDafActionPerformed

    private void fnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamaActionPerformed

    private void ftempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftempatActionPerformed

    private void falamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_falamatActionPerformed

    private void fsekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fsekolahActionPerformed

    private void fnilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnilaiActionPerformed

    private void fwaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fwaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fwaliActionPerformed

    private void fhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fhpActionPerformed

    private void BinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinsertActionPerformed
        try {
            SimpleDateFormat tg = new SimpleDateFormat("yyyy-MM-dd");
            String date = tg.format(tanggal.getDate());
            String nama = fnama.getText();
            String JenKel;
            if (laki.isSelected()){
                 JenKel = "L";
            }else{
                 JenKel = "P";
            }
            String tempatlahir = ftempat.getText();
            String alamat = falamat.getText();
            String asalsekolah = fsekolah.getText();
            String nilaiuan = fnilai.getText();
            String namaortu = fwali.getText();
            String notelp = fhp.getText();
            String id = NoDaf.getText();
            String sql = "INSERT INTO pendaftaran_siswa VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')";
            sql = String.format(
            sql,
            id,       
            nama,
            tempatlahir,
            date,
            JenKel,
            alamat,
            asalsekolah,
            nilaiuan,
            namaortu,
            notelp 
            );
            Connection conn = con.getcon();
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.execute();
     
            JOptionPane.showMessageDialog(null,"Data berhasil disimpan !");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Data gagal disimpan !" + ex);
        }finally{
            getData();
            resetData();
        }
    }//GEN-LAST:event_BinsertActionPerformed

    private void BupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupdateActionPerformed
      
        try {
            int jumlah =jTable1.getSelectedRow();
            if(jumlah == -1 ){
                return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tgllahir = sdf.format(tanggal.getDate());
            
            String id = NoDaf.getText();
            String nama = fnama.getText();
           String JenKel;
            if (laki.isSelected()){
                 JenKel = "L";
            }else{
                 JenKel = "P";
            }
            String alamat = falamat.getText();
            String telp = fhp.getText();
            String namaortu = fwali.getText();
            String nilaiuan = fnilai.getText();
            String asalsekolah = fsekolah.getText();
            String tempatlhr = ftempat.getText();
           
            String queryu = "UPDATE pendaftaran_siswa SET nama_lengkap = ?, tempat_lahir=?, tgl_lahir=?, jns_kelamin=?, alamat=?,asal_sekolah=?, "
                    + "nilai_uan=?, nama_ortu_wali=?, no_telp=? WHERE no_pendaftaran = ?";
            Connection conn = con.getcon();
            PreparedStatement stmt = conn.prepareStatement(queryu);
            stmt.setString(1,nama);
            stmt.setString(2,tempatlhr);
            stmt.setString(3,tgllahir);
            stmt.setString(4,JenKel);
            stmt.setString(5,alamat);
            stmt.setString(6,asalsekolah);
            stmt.setString(7,nilaiuan);
            stmt.setString(8,namaortu);
            stmt.setString(9,telp);
            stmt.setString(10,id);
            stmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil diubah !");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Data Gagal Terhapus !"+ex);      
        }finally{
            getData();
        }
        
    }//GEN-LAST:event_BupdateActionPerformed

    private void BdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdeleteActionPerformed
        
        int jumlah =jTable1.getSelectedRow();
        if(jumlah == -1 ){
            return;
        }
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String id = (String)model.getValueAt(jumlah,0);
        
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Anda Yakin ingin Menghapus Data ? ", "Konfirmasi ", JOptionPane.OK_CANCEL_OPTION,
                           JOptionPane.QUESTION_MESSAGE);
        if(konfirmasi == JOptionPane.OK_OPTION){
            try{
                Connection conn = con.getcon();
                String queryd = "DELETE FROM pendaftaran_siswa where no_pendaftaran = ?";
                PreparedStatement stmt = conn.prepareStatement(queryd);
                stmt.setString(1, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus !");
                
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Data Gagal Terhapus !"+ex);
            }finally{
                getData();
                
                resetData();
                
            }
        }
        if(konfirmasi == JOptionPane.CANCEL_OPTION){
            
        }
        
    }//GEN-LAST:event_BdeleteActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        resetData();
        getData();
        Binsert.setEnabled(true);
    }//GEN-LAST:event_BresetActionPerformed

    private void BcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcariActionPerformed
        
        try {
            // TODO add your handling code here:
            String sql ="";
            String combocari;
            combocari = (String)comCari.getSelectedItem();
            if(combocari == "Nama"){
                 sql =sql + "SELECT * FROM pendaftaran_siswa where nama_lengkap LIKE '%"+fcari.getText() +"%'";
            }else if(combocari == "Jenis kelamin"){
                sql =sql + "SELECT * FROM pendaftaran_siswa where jns_kelamin LIKE '%"+fcari.getText() +"%'";
            }else if(combocari == "Nilai"){
                sql =sql + "SELECT * FROM pendaftaran_siswa where nilai_uan LIKE '%"+fcari.getText() +"%'";
            }
            
            else{
                 sql =sql + "SELECT * FROM pendaftaran_siswa where no_pendaftaran LIKE '%"+fcari.getText() +"%'";
            }

            Connection conn = con.getcon();
            Statement stmtcari = conn.createStatement();
            ResultSet hasilcari = stmtcari.executeQuery(sql);
              DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//          Reset Data Tabel
                                model.setRowCount(0);

            while(hasilcari.next()){
                String id = hasilcari.getString("no_pendaftaran");
                String nama = hasilcari.getString("nama_lengkap");
                String tempatlhr = hasilcari.getString("tempat_lahir");
                 String tgl_lahir = hasilcari.getString("tgl_lahir");
                String jnskelamin = hasilcari.getString("jns_kelamin");
                String alamat = hasilcari.getString("alamat");
                String asalsekolah = hasilcari.getString("asal_sekolah");
                String nilaiuan = hasilcari.getString("nilai_uan");
                String namaortu = hasilcari.getString("nama_ortu_wali");
                String notelp = hasilcari.getString("no_telp");
                
                model.addRow(new Object[]{id,nama,tempatlhr,jnskelamin,alamat,asalsekolah,nilaiuan,namaortu,notelp});
            }
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            buatId();
        }
        
    }//GEN-LAST:event_BcariActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        try {
            Binsert.setEnabled(false);
            Bupdate.setEnabled(true);
            Bdelete.setEnabled(true);
            int jumlah = jTable1.getSelectedRow();
            if(jumlah == -1){
                return;
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            String id = (String)model.getValueAt(jumlah,0);
            NoDaf.setText(id);
            String nama = (String)model.getValueAt(jumlah,1);
            fnama.setText(nama);
            String tempatlahir = (String)model.getValueAt(jumlah,2);
            ftempat.setText(tempatlahir);
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(jumlah,3));
            tanggal.setDate(date);
            String jnskelamin = (String)model.getValueAt(jumlah,4);
            if(jnskelamin.equals("L")){
                laki.setSelected(true);
            }
            else if(jnskelamin.equals("P")){
                perempuan.setSelected(true);
            }
            String alamat = (String)model.getValueAt(jumlah,5);
            falamat.setText(alamat);
            String asalsekolah = (String)model.getValueAt(jumlah,6);
            fsekolah.setText(asalsekolah);
            String nilaiuan = (String)model.getValueAt(jumlah,7);
            fnilai.setText(nilaiuan);
            String namaortu = (String)model.getValueAt(jumlah,8);
            fwali.setText(namaortu);
            String notelp = (String)model.getValueAt(jumlah,9);
            fhp.setText(notelp);
        } catch (ParseException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked
private void getData(){
        try{
           Connection conn = con.getcon();
           Statement stmt = conn.createStatement();
           ResultSet hasil = stmt.executeQuery("SELECT * FROM pendaftaran_siswa");    
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//          Reset Data Tabel
          model.setRowCount(0);
          
          while(hasil.next()){
               String id = hasil.getString("no_pendaftaran");
               String nama = hasil.getString("nama_lengkap");
               String tempatlhr = hasil.getString("tempat_lahir");
               String tgl_lahir = hasil.getString("tgl_lahir");
               String jnskelamin = hasil.getString("jns_kelamin");
               String alamat = hasil.getString("alamat");
               String asalsekolah = hasil.getString("asal_sekolah");
               String nilaiuan = hasil.getString("nilai_uan");
               String namaortu = hasil.getString("nama_ortu_wali");
               String notelp = hasil.getString("no_telp");

               model.addRow(new Object[]{id,nama,tempatlhr,tgl_lahir,jnskelamin,alamat,asalsekolah,nilaiuan,namaortu,notelp});
          }
         
        } catch (SQLException ex){
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
public void buatId(){
       
        
        try {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuMMdd");
            LocalDate localDate = LocalDate.now();
            String id_pendaftaran = dtf.format(localDate);
            Connection c = con.getcon();
            Statement stmt2 = c.createStatement();
            ResultSet sets2 = stmt2.executeQuery("SELECT COUNT(no_pendaftaran)+1 from pendaftaran_siswa");
            if(sets2.next()){
                fNilai = Integer.parseInt(sets2.getString(1));
              
            }
            String nilaibaru = String.format("%04d", fNilai);
            String idbaru = id_pendaftaran+ nilaibaru;
            NoDaf.setText(idbaru);
                
           
           
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
public void resetData(){
        buatId();
        Binsert.setEnabled(true);
        fnama.setText("");
        ftempat.setText("");
        falamat.setText("");
        fsekolah.setText("");
        fnilai.setText("");
        fwali.setText("");
        fhp.setText("");
        tanggal.setDate(null);
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcari;
    private javax.swing.JButton Bdelete;
    private javax.swing.JButton Binsert;
    private javax.swing.JButton Breset;
    private javax.swing.JButton Bupdate;
    private javax.swing.JTextField NoDaf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comCari;
    private javax.swing.JTextField falamat;
    private javax.swing.JTextField fcari;
    private javax.swing.JTextField fhp;
    private javax.swing.JTextField fnama;
    private javax.swing.JTextField fnilai;
    private javax.swing.JTextField fsekolah;
    private javax.swing.JTextField ftempat;
    private javax.swing.JTextField fwali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton laki;
    private javax.swing.JRadioButton perempuan;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
